const STATUS_URL="https://raw.githubusercontent.com/oimo0/ASROStatus/status-data/status.json";
const STALE=12*60*1000;
const META={operational:["正常","operational"],busy:["混雑","busy"],maintenance:["メンテナンス","maintenance"],outage:["障害","outage"],building:["制作中","building"],unknown:["確認不可","unknown"]};
const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
function fmt(v){const d=new Date(v);if(Number.isNaN(d.getTime()))return"--";return new Intl.DateTimeFormat("ja-JP",{timeZone:"Asia/Tokyo",month:"numeric",day:"numeric",hour:"2-digit",minute:"2-digit",second:"2-digit"}).format(d)}
function active(n){const now=Date.now(),a=n.startsAt?new Date(n.startsAt).getTime():-Infinity,b=n.endsAt?new Date(n.endsAt).getTime():Infinity;return n.enabled!==false&&now>=a&&now<=b}
function withNotices(services,notices){return services.map(s=>{const n=notices.find(n=>active(n)&&n.overrideStatus&&Array.isArray(n.affected)&&n.affected.includes(s.id));return n?{...s,state:n.overrideStatus}:s})}
function renderServices(services,at){servicesEl.innerHTML=services.map(s=>{const m=META[s.state]||META.unknown;return '<article class="service"><div class="service-top"><div><div class="name">'+esc(s.name)+'</div><div class="desc">'+esc(s.description)+'</div></div><span class="pill '+m[1]+'">'+m[0]+'</span></div><div class="foot">最終確認 '+fmt(at)+'</div></article>'}).join("")}
function renderNotices(ns){const a=ns.filter(active);noticesEl.innerHTML=a.length?a.map(n=>'<article class="notice"><div class="notice-type">'+esc((n.type||"INFO").toUpperCase())+'</div><h3>'+esc(n.title||"お知らせ")+'</h3><p>'+esc(n.message||"")+'</p>'+(n.startsAt||n.endsAt?'<time>'+(n.startsAt?fmt(n.startsAt)+" から":"")+(n.endsAt?" "+fmt(n.endsAt)+" まで":"")+'</time>':"")+'</article>').join(""):'<article class="empty card">現在、掲載中のお知らせはありません。</article>'}
function overall(ss,stale){if(stale)return["監視情報を確認できません","以下には最後に取得できたシステム状態を表示しています。","!"];if(ss.some(s=>s.state==="outage"))return["一部のシステムで障害が発生しています","影響を受けているサービスの復旧状況を確認しています。","!"];if(ss.some(s=>s.state==="maintenance"))return["メンテナンス中のシステムがあります","対象サービスは一時的に利用しにくい場合があります。","↻"];if(ss.some(s=>s.state==="unknown"))return["一部のシステム状態を確認できません","監視経路から状態を取得できないサービスがあります。","?"];if(ss.some(s=>s.state==="busy"))return["一部のシステムが混雑しています","サービスは稼働していますが、通常より時間がかかる場合があります。","•"];return["稼働中のシステムは正常です","ASROの公開中サービスに大きな障害は確認されていません。","✓"]}
const servicesEl=document.getElementById("services"),noticesEl=document.getElementById("notices"),warning=document.getElementById("warning");
async function load(){let notices=[];try{const r=await fetch("data/notices.json?"+Date.now(),{cache:"no-store"});if(r.ok)notices=(await r.json()).notices||[]}catch{}renderNotices(notices);try{const r=await fetch(STATUS_URL+"?"+Date.now(),{cache:"no-store"});if(!r.ok)throw 0;const d=await r.json(),t=new Date(d.generatedAt).getTime(),stale=!Number.isFinite(t)||Date.now()-t>STALE,ss=withNotices(Array.isArray(d.services)?d.services:[],notices),o=overall(ss,stale);renderServices(ss,d.generatedAt);document.getElementById("updatedAt").textContent="最終更新: "+fmt(d.generatedAt);document.getElementById("overallTitle").textContent=o[0];document.getElementById("overallText").textContent=o[1];document.getElementById("heroIcon").textContent=o[2];warning.classList.toggle("hidden",!stale);if(stale)warning.textContent="監視システムからの更新が止まっています。表示内容は最後に取得できた状態です。"}catch{servicesEl.innerHTML='<article class="empty card">現在、稼働状況データを取得できません。</article>';document.getElementById("overallTitle").textContent="監視情報を取得できません";document.getElementById("overallText").textContent="ステータスページ自体は稼働しています。監視データの復旧を確認しています。";document.getElementById("heroIcon").textContent="!";warning.textContent="ASROStatusBackからの更新データを取得できません。";warning.classList.remove("hidden")}}
load();setInterval(load,60000);